### ISSUE TITLE
Renaming files selection colour issue

### ISSUE THREAD

**Issue by SupremeSoul** [EliverLara/Ant#1]
When we rename files, it doesn't colourize. Selection colour doesn't appear.  Please fix this issue.

**Comment by arnSky** [comment]
The issue still persists as at commit ab594390c677f94e048ec5af14dbd9e5d41796a1.
Issue being: While renaming a file, the text selection doesn't get highlighted, which makes renaming the file somewhat difficult. 

Theme tested on:-
OS: Ubuntu 16.04 LTS
Shell: Unity 7.4.0
Graphics Driver: nVidia 381.22 (proprietary)

**Comment by EliverLara** [comment]
Thank you @arnSky, I finally understand the issue, reopening ...

**Comment by EliverLara** [comment]
Fixed :smiley:

**Comment by arnSky** [comment]
Thanks :+1: :+1:   @EliverLara for for fixing the issue,

I can confirm that the issue is fixed as at commit 18301f9d511e166643894da4e318dd3e54c2118d
(in a much better style than any other average theme)

And [kudos](https://en.wikipedia.org/wiki/Kudos) to you for making such a :1st_place_medal: great :1st_place_medal: theme available,
